"""empty message

Revision ID: 1ba9c5255dd7
Revises: 15f36aaa30b0
Create Date: 2015-04-16 14:26:19.910354

"""

# revision identifiers, used by Alembic.
revision = '1ba9c5255dd7'
down_revision = '15f36aaa30b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
