"""empty message

Revision ID: 20701441479e
Revises: 59f1a520b841
Create Date: 2015-04-21 13:31:57.568870

"""

# revision identifiers, used by Alembic.
revision = '20701441479e'
down_revision = '59f1a520b841'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
