"""empty message

Revision ID: 241c68d91091
Revises: ee8551d929b
Create Date: 2015-04-14 15:09:18.858020

"""

# revision identifiers, used by Alembic.
revision = '241c68d91091'
down_revision = 'ee8551d929b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
