"""empty message

Revision ID: 293805674c94
Revises: 241c68d91091
Create Date: 2015-04-14 15:10:06.469044

"""

# revision identifiers, used by Alembic.
revision = '293805674c94'
down_revision = '241c68d91091'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
