"""empty message

Revision ID: 2c259a142c2c
Revises: 5230ec4c14ec
Create Date: 2015-04-08 17:08:23.057915

"""

# revision identifiers, used by Alembic.
revision = '2c259a142c2c'
down_revision = '5230ec4c14ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
