"""empty message

Revision ID: 3bd050a95c2c
Revises: 4133ea139570
Create Date: 2015-04-23 16:58:25.226165

"""

# revision identifiers, used by Alembic.
revision = '3bd050a95c2c'
down_revision = '4133ea139570'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
