"""empty message

Revision ID: 4133ea139570
Revises: 51d1b61e4570
Create Date: 2015-04-23 16:58:17.258722

"""

# revision identifiers, used by Alembic.
revision = '4133ea139570'
down_revision = '51d1b61e4570'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
