"""empty message

Revision ID: 4a858c94fc32
Revises: 20fcf7b1b131
Create Date: 2015-04-22 13:19:06.379735

"""

# revision identifiers, used by Alembic.
revision = '4a858c94fc32'
down_revision = '20fcf7b1b131'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
