"""empty message

Revision ID: 5230ec4c14ec
Revises: 49e1fc222b58
Create Date: 2015-04-08 15:13:07.163852

"""

# revision identifiers, used by Alembic.
revision = '5230ec4c14ec'
down_revision = '49e1fc222b58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
