"""empty message

Revision ID: 59f1a520b841
Revises: 9f5ae7dbb9b
Create Date: 2015-04-21 13:31:48.743152

"""

# revision identifiers, used by Alembic.
revision = '59f1a520b841'
down_revision = '9f5ae7dbb9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
