"""empty message

Revision ID: 9f5ae7dbb9b
Revises: 1ba9c5255dd7
Create Date: 2015-04-16 14:26:30.557589

"""

# revision identifiers, used by Alembic.
revision = '9f5ae7dbb9b'
down_revision = '1ba9c5255dd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
