"""empty message

Revision ID: ee8551d929b
Revises: 19b7974466c8
Create Date: 2015-04-14 14:28:36.622269

"""

# revision identifiers, used by Alembic.
revision = 'ee8551d929b'
down_revision = '19b7974466c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
